POST http://localhost:5000/api/post/
# POST http://localhost:5000/api/user/
Content-Type: application/json

# {
#     "firstName": "Kael",
#     "lastName" : "Makiling",
#     "email": "test@gmail.com",
#     "password": "secret"
# }

{
    "createdAt": "",
    "createdBy":"",
    "content":""
}